export const mutationTypes = {
  GET_PRODUCTS: 'GET_PRODUCTS',
  GET_PRODUCT_BY_ID: 'GET_PRODUCT_BY_ID',
  UPADATE_PRODUCT: 'UPADATE_PRODUCT',
  POST_CUSTOMER: 'POST_CUSTOMER',
  GET_CUSTOMER_BY_EMAIL: 'GET_CUSTOMER_BY_EMAIL',
  LOGIN_CUSTOMER: 'LOGIN_CUSTOMER',
  ADD_TO_CART: 'ADD_TO_CART',
  UPDATE_CART: 'UPDATE:CART',
  DELETE_PRODUCT: 'DELETE_PRODUCT',
  UPDATE_CUSTOMER: 'UPDATE_CUSTOMER',
  FILTER_PRODUCTS: 'FILTER_PRODUCTS',
};
