export const mutationTypes = {
  GET_PRODUCTS: 'GET_PRODUCTS',
  GET_PRODUCT_BY_ID: 'GET_PRODUCT_BY_ID',
  POST_CUSTOMER: 'POST_CUSTOMER',
  GET_CUSTOMER_BY_EMAIL: 'GET_CUSTOMER_BY_EMAIL',
  LOGIN_CUSTOMER: 'LOGIN_CUSTOMER',
};
